name: Go
on:
  push:
  pull_request:
  schedule:
    - cron:  '0 5 * * *'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v3
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Test
      run: go test -v -run '^(TestGetGuestToken|TestLoginOpenAccount|TestGetProfile|TestGetProfilePrivate|TestGetProfileErrorSuspended|TestGetProfileErrorNotFound|TestGetUserIDByScreenName|TestGetTweets)$'
